const mongoose = require('mongoose');
var Schema = mongoose.Schema;
var Property = mongoose.Schema({
    status: String,
    approvedDisApprovedBy: { type: Schema.Types.ObjectId, ref: 'Agent' },
    firm: { type: Schema.Types.ObjectId, ref: 'Firm' },
    agent: { type: Schema.Types.ObjectId, ref: 'Agent' },
    exclusivityFrom:Date,
    exclusivityUntill:Date,
    exclusivityDays:Number,
    exclusivityAgreement:String,
    mainImage: String,
    galleryImages: [String],
    additionalImages: [String],
    video: String,
    visitsPlanned: [{ type: Schema.Types.ObjectId, ref: 'PropertVisitsPlanned' }],
    saleAmountRequested: Number,
    saleCurrency: String,
    saleNewPrice: Number,
    saleDateOfChangingNewPrice: Date,
    saleEvacuationDate: Date,
    leaseAmountRequested:Number,
   leaseCurrency:String,
   leaseNewPrice:Number,
   leaseDateOfChangingNewPrice:Date,
    owners: [{ type: Schema.Types.ObjectId, ref: 'PropertyOwner' }],
    type: { type: Schema.Types.ObjectId, ref: 'PropertyType' },
    physicalAttrSurface:Number,
    physicalAttrSurfaceSource:String,
    physicalAttrRegisteredSurface:String,
    physicalAttrLandSurface:String,
    physicalAttrNumberOfRooms:Number,
    physicalAttrFloors:Number,
    physicalAttrNumberOfStairs:Number,
    physicalAttrElevator:String,
    physicalAttrInPropertLevels:Number,
    physicalAttrBedRooms:Number,
    physicalAttrToiletRooms:Number,
    physicalAttrBathRooms:Number,
    physicalAttrOverAllStatus:String,
    physicalAttrView:String,
    physicalAttrBalconies:String,
    systemAc:Boolean,
    systemAcDescription:String,
    systemHeating:Boolean,
    systemHeatingDescription:String,
    systemClosets:Boolean,
    systemGratedWindows:Boolean,
    systemFurniture:String,
    additionalBuiltBy:String,
    additionalYearBuilt:String,
    additionalRegisteredAt:String,
    additionalLandOwnerShip:String,
    additionalBuildingOption:String,
    additionalBuildingRightsAvailable:String,
    additionalParking:Number,
    additionalStorage:Number,
    additionalGarden:Number,
    additionalPrivateEntrance:Boolean,
    additionalWheelChair:Boolean,
    additionalDirections:String,
    description: String,
    commentsForAgents: String,
    publishOnHomePage: Boolean,
    publishInNAR: Boolean,
    locationCity: {type:Schema.Types.ObjectId,ref:'City'},
    locationNeighborhood: {type:Schema.Types.ObjectId,ref:'Neighborhood'},
    locationStreet:String,
    locationNumber:String,
    locationApt:String,
    locationEntrance:String,
    locationBlock:String,
    locationPlot:String,
    locationSubPlot:String,
    locationLatitude:String,
    locationLongitude:String,
    locationPublishHouseNumber:Boolean,
    createdDate:Date,
});

module.exports = mongoose.model('Property', Property);